apiVersion: apps/v1
kind: Deployment
metadata:
  name: anythingllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anythingllm
  template:
    metadata:
      labels:
        app: anythingllm
    spec:
      containers:
        - name: anythingllm
          image: mintplexlabs/anythingllm
          ports:
            - containerPort: 3001
          env:
            - name: STORAGE_DIR
              value: /app/server/storage
            - name: JWT_SECRET
              value: "make this a large list of random numbers and letters 20+"
            - name: LLM_PROVIDER
              value: ollama
            - name: OLLAMA_BASE_PATH
              value: http://192.168.0.233:11434
            - name: OLLAMA_MODEL_PREF
              value: llama2
            - name: OLLAMA_MODEL_TOKEN_LIMIT
              value: "4096"
            - name: EMBEDDING_ENGINE
              value: ollama
            - name: EMBEDDING_BASE_PATH
              value: http://192.168.0.233:11434
            - name: EMBEDDING_MODEL_PREF
              value: nomic-embed-text:latest
            - name: EMBEDDING_MODEL_MAX_CHUNK_LENGTH
              value: "8192"
            - name: VECTOR_DB
              value: lancedb
            - name: WHISPER_PROVIDER
              value: local
            - name: TTS_PROVIDER
              value: native
            - name: PASSWORDMINCHAR
              value: "8"
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - name: storage
              mountPath: /app/server/storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: anythingllm-storage-pvc