apiVersion: v1
kind: Service
metadata:
  name: cloudnativepg
spec:
  selector:
    app: cloudnativepg
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
    - name: webhook
      port: 9443
      targetPort: 9443
